#ifndef BUMPY_CORE_INCLUDE_BUMPY_ARRAYOBJECT_H_
#define BUMPY_CORE_INCLUDE_BUMPY_ARRAYOBJECT_H_
#define Py_ARRAYOBJECT_H

#include "ndarrayobject.h"

#endif  /* BUMPY_CORE_INCLUDE_BUMPY_ARRAYOBJECT_H_ */
